### ISSUE TITLE
Shadows are missing

### ISSUE THREAD

**Issue by Mailaender** [Mailaender/OpenHV#39]
Most of the original buildings (not all) contain shadow pixelart. We should be able to set them up with `ShadowStart` in the sequences. Offsets may be a problem.

**Comment by Dzierzan** [comment]
I could create one spritesheet which could collect all shadows without the need of editing every other spritesheet. Of course the offsets might be the problem, but with some patience, everything can be adjusted properly, just it might be tedious to do.

**Comment by Mailaender** [comment]
That won't work. They need to be on the same sprite sheet for `ShadowStart` to work.

**Comment by Dzierzan** [comment]
But WithIdleOverlay should work.

**Comment by Mailaender** [comment]
Well it almost did. Had to replace it https://github.com/Mailaender/OpenHV/commit/0799ecba896e9b4c65a2cfeed4829e0343cff6ad as to be honest `WithIdleOverlay` wasn't designed for this in mind.

**Comment by GraionDilach** [comment]
You sure the powerdown issue couldn't have been fixed with a shadow palette having `AllowModifiers: false`?

**Comment by Mailaender** [comment]
I haven't tested that. But looking https://github.com/OpenRA/OpenRA/blob/23b3c237b7071fd308c4664b0b6c5d719c0f3c74/OpenRA.Mods.Common/Traits/Modifiers/WithColoredOverlay.cs#L48-L51 at I don't think it would help. The palette isn't modified. A whole sprite is overlayed.

**Comment by GraionDilach** [comment]
Ahyeah, I totally forgot that `IsDecoration` flag hidden within the code - which is only set by ˛`Burns` upstream among the ingame traits besides `WithDecoration`.
