### ISSUE TITLE
Production Icons

### ISSUE THREAD

**Issue by Mailaender** [Mailaender/OpenHV#41]
![Build palette](https://cdn.discordapp.com/attachments/663031683313827851/668146828037849128/unknown.png)

as there none at the moment.

**Comment by GraionDilach** [comment]
Do you intend to remain with the RA1 64x48 icon size?

**Comment by Dzierzan** [comment]
Why not use actor's idle sprite? I dunno if it's in OpenRA but I remember IceReaper using units' idle sprite as an icon which was animated too. Maybe this was created for KKND2 only. I can't recall it properly.

**Comment by GraionDilach** [comment]
IIRC animated icons are only for KKND also we would have issues with sprite sizes. The idea could work, but we need to duplicate the files to a bounding box. An edge design might also be preferable.

**Comment by Dzierzan** [comment]
Another idea i have is upscaling idle sprites (let's say South-West direction) for units cause they are too small for such UI. I know a guy who's actually good in this.
