### ISSUE TITLE
Default remap

### ISSUE THREAD

**Issue by Dzierzan** [Mailaender/OpenHV#66]
The default remap (for grey) should be using the full spectrum of grey color cause it appears the last colors (the brightest ones) are not remapped, thus they are still grey (it is currently visable if you get yourself a beast actor).

**Comment by Mailaender** [comment]
As those are used for the outline I capped the remap first and last to avoid glitches. I might have capped too much though.

**Comment by Dzierzan** [comment]
Actuall my bad. Just some Daniel's artwork uses white pixels which are not part of defaul remap. I am closing this.
