### ISSUE TITLE
Lack of harbor building

### ISSUE THREAD

**Issue by Dzierzan** [Mailaender/OpenHV#67]
Hard Vacuum game has assets for boats and ship, but the problem is there's no actual building which could produce those units.
So here I created a custom harbor building. I'm no Daniel Cook, I tried my best to mimic his artstyle. Please, share your thoughts. Once it's fully accepted, I will create the rest of requires sprites for it

![harbor](https://user-images.githubusercontent.com/17529329/73753112-6a0faa00-4762-11ea-8f70-f30e32a5e10b.png)

(the blue orb on top of that is supposed to be animated, indicating a unit being produced, just like factories).

**Comment by Dzierzan** [comment]
![harbor](https://user-images.githubusercontent.com/17529329/73851369-a3f9b280-482d-11ea-8c18-e3f3be4d5ada.png)

**Comment by GraionDilach** [comment]
Not too fond of the rock texture on the left side. No other building has rock textures in a quick glimpse. The Radar Dome is the closest, but that's totally different. What is the upwards pipe at the top-right corner supposed to symbolize?

**Comment by Dzierzan** [comment]
I might change the Rocky texture. The pipe... I didnt think too much of it to be honest.

**Comment by GraionDilach** [comment]
The ports look plain. Maybe those could get planks instead.
