### ISSUE TITLE
Why no packaging files?

### ISSUE THREAD

**Issue by fusion809** [Mailaender/OpenHV#71]
Hi,

It would be delightful if I could build an AppImage for this mod, as then I could play it on NixOS without too much fuss, but currently this repo has no packaging/linux directory. Any interest in rectifying this situation?

Thanks for your time,
Brenton

**Comment by Mailaender** [comment]
Added the packaging scripts (untested), but don't be disappointed. This isn't a complete game yet. That's also why release packaging wasn't a priority.
